# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmlhelper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmldoc',
            old_name='doc_text',
            new_name='xml_document',
        ),
        migrations.AddField(
            model_name='xmldoc',
            name='xpath_query',
            field=models.TextField(default='vvv'),
            preserve_default=False,
        ),
    ]
